# -*- coding: utf-8 -*-
"""MIS584_Project_V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pc5Haxzx8XqHFblmm8Jq_-mdUr-SUSM2

#584 Project - Walmart Retail Analytics - Predicting Product Performance

For this project, we use the “Walmart Recruiting – Store Sales Forecasting” dataset from Kaggle, which contains historical weekly sales for 45 US Walmart stores at the store–department level from February 2010 to November 2012. The data is split across three main files: train.csv (≈422K rows of Weekly_Sales by Store–Dept–Date with holiday flags), features.csv (store-level economic, promotional, and seasonal covariates such as temperature, fuel price, markdowns, CPI, unemployment, and holiday indicators), and stores.csv (store type and size).

We integrate these sources in PySpark into a single analytics table, which serves as the foundation for forecasting weekly sales and profiling department-level product performance. While the public dataset is moderate in size, **our data model, partitioning strategy, and Spark-based pipeline are explicitly designed to scale to production-level Walmart data volumes.**

Files Used:

train.csv: ~421,570 rows – Store, Dept, Date, Weekly_Sales, IsHoliday

features.csv: ~8,190 rows – Store, Date, Temperature, Fuel_Price, MarkDown1–5, CPI, Unemployment, IsHoliday

stores.csv: 45 rows – Store, Type, Size

##Part 1: Creating a master dataframe in pyspark from the external data source

### Creating PySpark environment
"""

!pip install pyspark

import os
os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-8-openjdk-amd64'
!java -version

!apt-get update
!apt-get install -y openjdk-11-jdk-headless
os.environ['JAVA_HOME'] = '/usr/lib/jvm/java-11-openjdk-amd64'
!java -version

# Creating PySpark session application
from pyspark.sql import SparkSession
spark = (SparkSession.builder.\
         appName("Walmart_Retail_Analytics").\
         getOrCreate())

"""### Importing external data into pyspark dataframe"""

from google.colab import drive
drive.mount('/content/drive')

###1. storing train.csv data into train_df

train_df = (spark.read.option("header", "true")\
            .option("inferSchema", "true")\
            .csv("/content/drive/MyDrive/MIS584_BigData/Project/train.csv"))
  # Print df information
train_df.show(5)

train_columns = len(train_df.columns)
print(f"Number of coulmns in train_df: {train_columns}")

train_rows = train_df.count()
print(f"Number of rows in train_df: {train_rows}")
print()


###2. storing features.csv data into features_df

features_df = (spark.read.option("header", "true")\
            .option("inferSchema", "true")\
            .csv("/content/drive/MyDrive/MIS584_BigData/Project/features.csv"))
  # Print df information
features_df.show(5)

features_columns = len(features_df.columns)
print(f"Number of coulmns in features_df: {features_columns}")

features_rows = features_df.count()
print(f"Number of rows in features_df: {features_rows}")
print()


###3. storing stores.csv data into stores_df

stores_df = (spark.read.option("header", "true")\
            .option("inferSchema", "true")\
            .csv("/content/drive/MyDrive/MIS584_BigData/Project/stores.csv"))
  # Print df information
stores_df.show(5)

stores_columns = len(stores_df.columns)
print(f"Number of coulmns in stores_df: {stores_columns}")

stores_rows = stores_df.count()
print(f"Number of rows in stores_df: {stores_rows}")

"""### Combining train, features and stores dataframes to create a master dataframe for analysis"""

##Combining Datasets imported
master_df = (train_df
           .join(stores_df, on="Store", how="left")
           .join(features_df, on=["Store", "Date"], how="left"))

##Using master_df as a master dataset
master_df.printSchema()
master_df.show(10)

print("Rows in master_df:", master_df.count())

num_columns = len(master_df.columns)
print(f"Columns in master_df: {num_columns}")

"""##Part 2: Performing sanity checks and Exploratory Data Analysis (EDA)

### Dataframe cleaning and structuing

In master_df dataframe we observe that 'IsHoliday' column appears twice from train and features df. We need to keep either of them to avoid future duplicate errors. We also observe that some numeric columns datatype is changed to string, we need to change it to correct datatype (numeric).

We'll complete this in 2 sections:
1. Keeping one holiday column and setting it to Boolean Datatype
2. Reverting datatypes of string datatype columns to numeric

#### Step 1.1 : Rename duplicate columns by position
"""

cols = master_df.columns

seen = {}
new_cols = []

for name in cols:
    if name not in seen:
        seen[name] = 1
        new_cols.append(name)
    else:
        # create a unique name for duplicate
        new_name = f"{name}_{seen[name]}"
        seen[name] += 1
        new_cols.append(new_name)

# Rename columns by position in one shot
master_df = master_df.toDF(*new_cols)

print(master_df.columns)

"""#### Step 1.2 : Merge the two IsHoliday columns & drop the extra"""

from pyspark.sql.functions import coalesce, col

if "IsHoliday_1" in master_df.columns:
    master_df = (master_df
        .withColumn(
            "IsHoliday_clean",
            coalesce(col("IsHoliday"), col("IsHoliday_1")).cast("boolean")
        )
        .drop("IsHoliday", "IsHoliday_1")
        .withColumnRenamed("IsHoliday_clean", "IsHoliday")
    )
else:
    # Fallback: ensure IsHoliday is boolean
    master_df = master_df.withColumn("IsHoliday", col("IsHoliday").cast("boolean"))

master_df.printSchema()
print(master_df.columns)

"""#### Step 2 : Fix numeric columns"""

from pyspark.sql.functions import col

to_double = [
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "CPI", "Unemployment"
]

for c in to_double:
    if c in master_df.columns:
        master_df = master_df.withColumn(c, col(c).cast("double"))

master_df.printSchema()
master_df.show(5)

"""#### Step 3 : Check the master_df for any other clean-ups"""

from pyspark.sql.functions import min as _min, max as _max, count as _count, sum as _sum, when

print("Rows:", master_df.count())
master_df.select(_min("Date").alias("min_date"),
                 _max("Date").alias("max_date")).show()

# Nulls in key numeric cols
check_cols = ["Weekly_Sales","Temperature","Fuel_Price","CPI","Unemployment",
              "MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"]
nulls = master_df.select([
    _sum(col(c).isNull().cast("int")).alias(c)
    for c in check_cols if c in master_df.columns
])
nulls.show(truncate=False)

# Uniqueness of (Store, Dept, Date)
dupes = (master_df
         .groupBy("Store", "Dept", "Date")
         .agg(_count("*").alias("row_count"))
         .filter(col("row_count") > 1))
print("Duplicate (Store,Dept,Date) rows:", dupes.count())

"""From the above result we can conclude that our integrated master_df is structurally consistent:

no duplicate keys, complete target and core features, and missingness concentrated in markdown variables, which aligns with real-world promotional sparsity.

We profiled missing values and identified MarkDown variables as sparse; these will be handled via domain-aware imputation or treated as zero markdown when appropriate.
"""

#Confirmation on null counts in master df before proceeding

null_counts = [
    _count(when(col(c).isNull(), c)).alias(c)
    for c in master_df.columns
]
master_df.agg(*null_counts).show()

"""### EDA"""

#### Step 1: Add core date features
from pyspark.sql.functions import year, month, weekofyear

master_df = (master_df
    .withColumn("Year", year("Date"))
    .withColumn("Month", month("Date"))
    .withColumn("WeekOfYear", weekofyear("Date"))

)

#### Step 2: Handle MarkDown nulls (make a clear modeling choice)
markdown_cols = ["MarkDown1","MarkDown2","MarkDown3","MarkDown4","MarkDown5"]

for c in markdown_cols:
    if c in master_df.columns:
        master_df = master_df.fillna({c: 0.0})

master_df.show(5)

# Saving cleaned master file as CSV using Pandas.
# With PySpark, it was a long process to save as CSV since it used multiple
# worker nodes to save 2 csv files and then these 2 files needed to be merged into single file.

import pandas as pd

pandas_master_df = master_df.toPandas()
pandas_master_df.to_csv("master_data_cleaned.csv", index=False)

#### Step 3: Quick distribution checks (for narrative + sanity)
master_df.select("Weekly_Sales").describe().show()

q = master_df.approxQuantile("Weekly_Sales", [0.25, 0.5, 0.75, 0.95, 0.99], 0.01)
print(q)

"""Store and Dept performance snapshots"""

#### Step 4: Store & Dept performance snapshots

##### Store Performance

from pyspark.sql.functions import sum as _sum, avg as _avg, col, format_number

# 1) Raw numeric metrics
store_perf_raw = (master_df.groupBy("Store")
    .agg(
        _sum("Weekly_Sales").alias("total_sales"),
        _avg("Weekly_Sales").alias("avg_weekly_sales")
    )
)

# 2) Top 5 stores (numeric sort)
top5_stores = (store_perf_raw
    .orderBy(col("total_sales").desc())
    .select(
        "Store",
        format_number("total_sales", 2).alias("total_sales"),
        format_number("avg_weekly_sales", 2).alias("avg_weekly_sales")
    )
)

print("Top 5 Stores by Total Sales:")
top5_stores.show(5)

# 3) Bottom 5 stores (numeric sort)
bottom5_stores = (store_perf_raw
    .orderBy(col("total_sales").asc())
    .select(
        "Store",
        format_number("total_sales", 2).alias("total_sales"),
        format_number("avg_weekly_sales", 2).alias("avg_weekly_sales")
    )
)

print("Bottom 5 Stores by Total Sales:")
bottom5_stores.show(5)

# 4) Proper summary (on numeric)
print("Performance summary across Stores: ")

store_summary = store_perf_raw.describe(["total_sales", "avg_weekly_sales"])

store_summary = (store_summary
    .withColumn("total_sales",
                format_number(col("total_sales").cast("double"), 2))
    .withColumn("avg_weekly_sales",
                format_number(col("avg_weekly_sales").cast("double"), 2))
)

store_summary.show(truncate=False)

##### Department Performance

# 1) Raw numeric metrics
dept_perf_raw = (master_df.groupBy("Dept")
    .agg(
        _sum("Weekly_Sales").alias("total_sales"),
        _avg("Weekly_Sales").alias("avg_weekly_sales")
    )
)

# 2) Top 5 depts
top5_depts = (dept_perf_raw
    .orderBy(col("total_sales").desc())
    .select(
        "Dept",
        format_number("total_sales", 2).alias("total_sales"),
        format_number("avg_weekly_sales", 2).alias("avg_weekly_sales")
    )
)

print("Top 5 Depts by Total Sales:")
top5_depts.show(5)

# 3) Bottom 5 depts
bottom5_depts = (dept_perf_raw
    .orderBy(col("total_sales").asc())
    .select(
        "Dept",
        format_number("total_sales", 2).alias("total_sales"),
        format_number("avg_weekly_sales", 2).alias("avg_weekly_sales")
    )
)

print("Bottom 5 Depts by Total Sales:")
bottom5_depts.show(5)

# 4) Proper summary
print("Performance summary across Departments: ")

department_summary = dept_perf_raw.describe(["total_sales", "avg_weekly_sales"])

department_summary = (department_summary
    .withColumn("total_sales",
                format_number(col("total_sales").cast("double"), 2))
    .withColumn("avg_weekly_sales",
                format_number(col("avg_weekly_sales").cast("double"), 2))
)

department_summary.show(truncate=False)

####Step 5: Holiday vs non-holiday impact
holiday_stats = (master_df.groupBy("IsHoliday")
                 .agg(_avg("Weekly_Sales").alias("avg_weekly_sales")))
holiday_stats.show()

####Step 6: Build baseline time-series features

from pyspark.sql.window import Window
from pyspark.sql.functions import lag, avg

w = Window.partitionBy("Store", "Dept").orderBy("Date")


#add lag features
master_df = (master_df
    .withColumn("Weekly_Sales_lag1", lag("Weekly_Sales", 1).over(w))
    .withColumn("Weekly_Sales_lag2", lag("Weekly_Sales", 2).over(w))
)


#add rolling mean baseline (4 weeks)
w_ma4 = w.rowsBetween(-4, -1)

master_df = master_df.withColumn(
    "Weekly_Sales_MA4",
    avg("Weekly_Sales").over(w_ma4)
)

master_df.show(10)

#### Step 7: Define model-ready dataframe

feature_cols = [
    "Date",
    "Weekly_Sales",
    "Store", "Dept",
    "Type", "Size",
    "IsHoliday",
    "Temperature", "Fuel_Price",
    "CPI", "Unemployment",
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "Year", "Month", "WeekOfYear",
    "Weekly_Sales_lag1", "Weekly_Sales_lag2", "Weekly_Sales_MA4"
]

model_df = master_df.select(feature_cols).na.drop(subset=["Weekly_Sales_lag1","Weekly_Sales_lag2","Weekly_Sales_MA4"])

model_df.printSchema()
print("model_df rows:", model_df.count())

"""## Part 3 : Visualizations

### Finding correlation between all the features
"""

from pyspark.ml.stat import Correlation
from pyspark.ml.feature import VectorAssembler, StringIndexer
from pyspark.ml import Pipeline
from pyspark.sql.functions import col
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# --- STEP 1: DATA PREP ---
# 1. Cast IsHoliday to Integer (True=1, False=0)
# 2. Drop rows where Lags/MA are null (Essential for correlation math)
# 3. Filter out any potential nulls in feature columns to be safe
clean_corr_df = master_df.withColumn("IsHoliday", col("IsHoliday").cast("integer")) \
                         .na.drop(subset=["Weekly_Sales_lag1", "Weekly_Sales_lag2", "Weekly_Sales_MA4"])

# --- STEP 2: DEFINE COLUMNS (Aligned with your Schema) ---
cat_cols = ['Type']

# We include ALL numerical features from your schema
# Note: We EXCLUDE 'Date', 'Store', 'Dept' as they are not predictive numbers in this context
num_cols = [
    'Weekly_Sales',
    'Size', 'Temperature', 'Fuel_Price', 'CPI', 'Unemployment',
    'MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5',
    'Year', 'Month', 'WeekOfYear',                 # Time Features
    'Weekly_Sales_lag1', 'Weekly_Sales_lag2',      # Lags
    'Weekly_Sales_MA4',                            # Moving Average
    'IsHoliday'                                    # Converted Integer
]

# --- STEP 3: PIPELINE FOR INDEXING ---
# Convert 'Type' (A,B,C) -> 'Type_index' (0,1,2)
indexers = [
    StringIndexer(inputCol=c, outputCol=f"{c}_index", handleInvalid="keep")
    for c in cat_cols
]

pipeline = Pipeline(stages=indexers)
df_ready = pipeline.fit(clean_corr_df).transform(clean_corr_df)

# --- STEP 4: VECTOR ASSEMBLY ---
# Combine all numeric cols + the new 'Type_index'
all_features = num_cols + [f"{c}_index" for c in cat_cols]

assembler = VectorAssembler(
    inputCols=all_features,
    outputCol="corr_features",
    handleInvalid="skip"
)

df_vector = assembler.transform(df_ready).select("corr_features")

# --- STEP 5: CALCULATE MATRIX ---
print("Calculating Correlation Matrix...")
matrix = Correlation.corr(df_vector, "corr_features").head()
corr_array = matrix[0].toArray()

# --- STEP 6: PLOT (Pandas) ---
pdf_corr = pd.DataFrame(corr_array, columns=all_features, index=all_features)

plt.figure(figsize=(18, 16)) # Large size to fit all labels
sns.heatmap(pdf_corr, annot=True, fmt=".2f", cmap='coolwarm', vmin=-1, vmax=1)
plt.title("Feature Correlation Matrix (Complete)")
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""### 1. Overall Weekly Sales Trend (Time-Series Line Plot)"""

from pyspark.sql.functions import sum as _sum
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick # Import for formatting

# Aggregate weekly total sales
weekly_trend = (master_df
    .groupBy("Date")
    .agg(_sum("Weekly_Sales").alias("total_sales"))
    .orderBy("Date"))

pdf_weekly = weekly_trend.toPandas()

plt.figure(figsize=(10, 4))
plt.plot(pdf_weekly["Date"], pdf_weekly["total_sales"])
plt.xlabel("Date")
plt.ylabel("Total Weekly_Sales")
plt.title("Total Weekly Sales Over Time")

# Get the current axes
ax = plt.gca()
# Format y-axis labels to avoid scientific notation and add comma separators
ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: format(int(x), ',')))

plt.tight_layout()
plt.show()

"""### 2. Top 10 Stores by Total Sales (Bar Chart)"""

from pyspark.sql.functions import sum as _sum
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

store_perf_raw = (master_df.groupBy("Store")
    .agg(_sum("Weekly_Sales").alias("total_sales")))

top10_stores_df = (store_perf_raw
    .orderBy("total_sales", ascending=False)
    .limit(10)
    .toPandas())

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(top10_stores_df["Store"].astype(str), top10_stores_df["total_sales"])
ax.set_xlabel("Store")
ax.set_ylabel("Total Weekly_Sales")
ax.set_title("Top 10 Stores by Total Sales")
ax.ticklabel_format(style='plain', axis='y')  # disable scientific

ax.yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, p: format(int(x), ','))
)

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### 3. Top 10 Departments by Total Sales (Bar Chart)"""

from pyspark.sql.functions import sum as _sum
import matplotlib.pyplot as plt

dept_perf_raw = (master_df.groupBy("Dept")
    .agg(_sum("Weekly_Sales").alias("total_sales")))

top10_depts_df = (dept_perf_raw
    .orderBy("total_sales", ascending=False)
    .limit(10)
    .toPandas())

plt.figure(figsize=(8, 4))
plt.bar(top10_depts_df["Dept"].astype(str), top10_depts_df["total_sales"])
plt.xlabel("Dept")
plt.ylabel("Total Weekly_Sales")
plt.title("Top 10 Departments by Total Sales")
plt.xticks(rotation=0)

plt.ticklabel_format(style='plain', axis='y')
plt.tight_layout()
plt.show()

#Clean version for Department plot

import matplotlib.ticker as mtick

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(top10_depts_df["Dept"].astype(str), top10_depts_df["total_sales"])
ax.set_xlabel("Department")
ax.set_ylabel("Total Weekly_Sales")
ax.set_title("Top 10 Departments by Total Sales")
ax.ticklabel_format(style='plain', axis='y')

ax.yaxis.set_major_formatter(
    mtick.FuncFormatter(lambda x, p: format(int(x), ','))
)

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### 4. Holiday vs Non-Holiday Average Sales (Bar Chart)"""

from pyspark.sql.functions import avg as _avg
import matplotlib.pyplot as plt

holiday_stats = (master_df.groupBy("IsHoliday")
    .agg(_avg("Weekly_Sales").alias("avg_weekly_sales"))
    .orderBy("IsHoliday"))

pdf_holiday = holiday_stats.toPandas()

plt.figure(figsize=(5, 4))
plt.bar(pdf_holiday["IsHoliday"].astype(str), pdf_holiday["avg_weekly_sales"])
plt.xlabel("IsHoliday")
plt.ylabel("Avg Weekly_Sales")
plt.title("Average Weekly Sales: Holiday vs Non-Holiday")
plt.tight_layout()
plt.show()

"""---

## PART 4: ML Model Selection and Testing on Master Data

### 1. Imports, Preprocessing & Caching
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pyspark.ml.feature import StringIndexer, VectorAssembler, OneHotEncoder, StandardScaler
from pyspark.ml import Pipeline
from pyspark.sql.functions import col
from pyspark.ml.regression import LinearRegression, RandomForestRegressor, DecisionTreeRegressor, GBTRegressor
from pyspark.ml.evaluation import RegressionEvaluator
from xgboost.spark import SparkXGBRegressor

# --- CONFIGURATION ---
SPLIT_DATE = "2012-02-01"
SEED = 42

# --- STEP 1: CLEANING & CASTING ---
# Cast IsHoliday -> Integer
# Drop nulls in Lag/MA columns (First 4 weeks of data cannot be used)
clean_df = master_df.withColumn("IsHolidayInt", col("IsHoliday").cast("integer")) \
                    .na.drop(subset=["Weekly_Sales_lag1", "Weekly_Sales_lag2", "Weekly_Sales_MA4"])

# --- STEP 2: CATEGORICAL INDEXING & ENCODING ---
# We Index strings -> Numbers, then Encode Numbers -> Vectors (OHE)
# This is crucial for Linear Regression performance
indexers = [
    StringIndexer(inputCol="Store", outputCol="StoreIndex", handleInvalid="skip"),
    StringIndexer(inputCol="Dept", outputCol="DeptIndex", handleInvalid="skip"),
    StringIndexer(inputCol="Type", outputCol="TypeIndex", handleInvalid="skip")
]

encoder = OneHotEncoder(inputCols=["StoreIndex", "DeptIndex", "TypeIndex"],
                        outputCols=["StoreVec", "DeptVec", "TypeVec"])

# --- STEP 3: VECTOR ASSEMBLY ---
# Define all input features
feature_cols = [
    "StoreVec", "DeptVec", "TypeVec",  # Encoded Categories
    "Size", "IsHolidayInt", "Temperature", "Fuel_Price", "CPI", "Unemployment",
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "Year", "Month", "WeekOfYear",
    "Weekly_Sales_lag1", "Weekly_Sales_lag2", "Weekly_Sales_MA4"
]

assembler = VectorAssembler(inputCols=feature_cols, outputCol="features", handleInvalid="skip")

# Build & Run Preprocessing Pipeline
prep_pipeline = Pipeline(stages=indexers + [encoder, assembler])
print("Running Preprocessing Pipeline...")
processed_data = prep_pipeline.fit(clean_df).transform(clean_df)

# --- STEP 4: TRAIN/TEST SPLIT & CACHING ---
# Time-based split for forecasting
train_data = processed_data.filter(col("Date") < SPLIT_DATE)
test_data = processed_data.filter(col("Date") >= SPLIT_DATE)

# CRITICAL: Cache data to speed up multi-model training
train_data.cache()
print(f"Data Cached. Train Rows: {train_data.count()}, Test Rows: {test_data.count()}")

# Initialize Evaluators
evaluator_rmse = RegressionEvaluator(labelCol="Weekly_Sales", predictionCol="prediction", metricName="rmse")
evaluator_mae = RegressionEvaluator(labelCol="Weekly_Sales", predictionCol="prediction", metricName="mae")

"""### 2. Linear Regression"""

print("\n--- Model 1: Linear Regression (Scaled) ---")

# 1. Apply Scaling (Standardization)
scaler = StandardScaler(inputCol="features", outputCol="scaled_features", withStd=True, withMean=False)
scaler_model = scaler.fit(train_data)
train_data_lr = scaler_model.transform(train_data)
test_data_lr = scaler_model.transform(test_data)

# 2. Train (Ridge Regularization)
# regParam=0.1 is a safe baseline to prevent overfitting on correlated features
lr = LinearRegression(featuresCol="scaled_features", labelCol="Weekly_Sales", regParam=0.1, elasticNetParam=0.0)
lr_model = lr.fit(train_data_lr)

# 3. Predict & Evaluate
lr_preds = lr_model.transform(test_data_lr)
lr_rmse = evaluator_rmse.evaluate(lr_preds)
lr_mae = evaluator_mae.evaluate(lr_preds)

print(f"LR RMSE: {lr_rmse:,.0f}")
print(f"LR MAE:  {lr_mae:,.0f}")

"""### 3. Tree Regression Models"""

print("\n--- Tree Models ---")

# --- MODEL 2: DECISION TREE ---
print("Training Decision Tree...")
dt = DecisionTreeRegressor(featuresCol="features", labelCol="Weekly_Sales", maxDepth=5, seed=SEED)
dt_model = dt.fit(train_data)
dt_preds = dt_model.transform(test_data)
dt_rmse = evaluator_rmse.evaluate(dt_preds)
dt_mae = evaluator_mae.evaluate(dt_preds)
print(f"DT RMSE: {dt_rmse:,.2f} | MAE: {dt_mae:,.2f}")

# --- MODEL 3: RANDOM FOREST ---
print("\nTraining Random Forest...")
rf = RandomForestRegressor(featuresCol="features", labelCol="Weekly_Sales", numTrees=30, maxDepth=5, seed=SEED)
rf_model = rf.fit(train_data)
rf_preds = rf_model.transform(test_data)
rf_rmse = evaluator_rmse.evaluate(rf_preds)
rf_mae = evaluator_mae.evaluate(rf_preds)
print(f"RF RMSE: {rf_rmse:,.2f} | MAE: {rf_mae:,.2f}")

# --- MODEL 4: GBT REGRESSOR ---
print("\nTraining GBT (Gradient Boosted Trees)...")
# Reduced maxIter to 20 for speed
gbt = GBTRegressor(featuresCol="features", labelCol="Weekly_Sales", maxIter=20, maxDepth=5, seed=SEED)
gbt_model = gbt.fit(train_data)
gbt_preds = gbt_model.transform(test_data)
gbt_rmse = evaluator_rmse.evaluate(gbt_preds)
gbt_mae = evaluator_mae.evaluate(gbt_preds)
print(f"GBT RMSE: {gbt_rmse:,.2f} | MAE: {gbt_mae:,.2f}")

# --- MODEL 5: XGBOOST ---
print("\nTraining XGBoost...")
xgb = SparkXGBRegressor(
    features_col="features",
    label_col="Weekly_Sales",
    num_workers=2,
    objective="reg:squarederror",
    max_depth=5,
    n_estimators=50,
    missing=0.0
)
xgb_model = xgb.fit(train_data)
xgb_preds = xgb_model.transform(test_data)
xgb_rmse = evaluator_rmse.evaluate(xgb_preds)
xgb_mae = evaluator_mae.evaluate(xgb_preds)
print(f"XGB RMSE: {xgb_rmse:,.2f} | MAE: {xgb_mae:,.2f}")

"""### 4. Final Leaderboard & Visualization"""

# --- FINAL LEADERBOARD ---
print("\n" + "="*45)
print("FINAL MODEL LEADERBOARD (Sorted by RMSE)")
print("="*45)

results = [
    ("Linear Regression", lr_rmse, lr_mae),
    ("Decision Tree", dt_rmse, dt_mae),
    ("Random Forest", rf_rmse, rf_mae),
    ("GBT Regressor", gbt_rmse, gbt_mae),
    ("XGBoost", xgb_rmse, xgb_mae)
]

results.sort(key=lambda x: x[1]) # Sort by RMSE

print(f"{'Model':<20} | {'RMSE':<10} | {'MAE':<10}")
print("-" * 45)
for name, r, m in results:
    print(f"{name:<20} | {r:,.0f}      | {m:,.0f}")

# --- FEATURE IMPORTANCE PLOT (XGBoost) ---
print("\nGenerating Feature Importance Plot...")

# 1. Get Feature Metadata (Crucial for OHE names)
# We extract the attributes from the 'features' column metadata
# This maps "f0" -> "StoreVec_1", "f1" -> "StoreVec_2", etc.
attrs = processed_data.schema["features"].metadata["ml_attr"]["attrs"]
features_list = []
# Combine numeric and binary (OHE) attributes into a single list sorted by index
for attr_type in attrs:
    features_list += attrs[attr_type]
features_list.sort(key=lambda x: x['idx'])
feature_names = [x['name'] for x in features_list]

# 2. Get Scores from Booster
booster = xgb_model.get_booster()
score = booster.get_score(importance_type='gain')

# 3. Map Scores to Names
importance_data = []
for fid, val in score.items():
    idx = int(fid[1:]) # Convert 'f0' -> 0
    if idx < len(feature_names):
        importance_data.append({'Feature': feature_names[idx], 'Gain': val})

# 4. Plot
df_imp = pd.DataFrame(importance_data).sort_values(by='Gain', ascending=False).head(15)

plt.figure(figsize=(12, 8))
sns.barplot(x='Gain', y='Feature', data=df_imp, palette='viridis')
plt.title('Top 15 Drivers of Weekly Sales (XGBoost Feature Importance)')
plt.xlabel('Gain (Predictive Power)')
plt.ylabel('Feature')
plt.tight_layout()
plt.show()

# ====================================================================
# CHECK TRAINING PERFORMANCE - Gap between Train and Test RSME values
# ====================================================================
print("\n--- Checking XGBoost on Training Data (Detect Overfitting) ---")

# 1. Predict on the Training Set
train_preds = xgb_model.transform(train_data)

# 2. Evaluate
train_rmse = evaluator_rmse.evaluate(train_preds)
train_mae = evaluator_mae.evaluate(train_preds)

print(f"Training RMSE: {train_rmse:,.0f}")
print(f"Training MAE:  {train_mae:,.0f}")

# 3. Compare with Test Score
print("-" * 30)
print(f"Gap (Test - Train): {xgb_rmse - train_rmse:,.0f}")
if (xgb_rmse - train_rmse) > 1000:
    print("WARNING: Potential Overfitting (Test error is much higher than Train error)")
else:
    print("GOOD: Model generalizes well (Gap is small)")

"""---



---



---



---

### Model Training & Evaluation on Unseen Data (Future Weekly Sales Prediction)
"""

# =========================================================
# PART C: FUTURE FORECASTING (UPDATED WITH XGBOOST)
# =========================================================
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.sql.functions import col, year, month, weekofyear, sum as _sum, lit
from xgboost.spark import SparkXGBRegressor
from pyspark.sql.types import DoubleType, IntegerType
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.ticker as mtick

# 1. Load Files
test_path = "/content/drive/MyDrive/MIS584_BigData/Project/test.csv"
features_path = "/content/drive/MyDrive/MIS584_BigData/Project/features.csv"
stores_path = "/content/drive/MyDrive/MIS584_BigData/Project/stores.csv"

test_raw = spark.read.option("header", "true").option("inferSchema", "true").csv(test_path)
features_df = spark.read.option("header", "true").option("inferSchema", "true").csv(features_path)
stores_df = spark.read.option("header", "true").option("inferSchema", "true").csv(stores_path)

# 2. Join Data
features_clean = features_df.drop("IsHoliday")
test_joined = (test_raw
    .join(stores_df, on="Store", how="left")
    .join(features_clean, on=["Store", "Date"], how="left")
)

# =========================================================
# STEP 2: ROBUST TYPE CASTING
# =========================================================

# 1. Force-cast problematic columns to Double
numeric_cols = [
    "CPI", "Unemployment", "Fuel_Price", "Temperature",
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "Size"
]

test_df_casted = test_joined
for c_name in numeric_cols:
    if c_name in test_joined.columns:
        test_df_casted = test_df_casted.withColumn(c_name, col(c_name).cast(DoubleType()))

# 2. Fill Nulls
fill_values = {
    "MarkDown1": 0.0, "MarkDown2": 0.0, "MarkDown3": 0.0, "MarkDown4": 0.0, "MarkDown5": 0.0,
    "CPI": 0.0, "Unemployment": 0.0, "Temperature": 0.0, "Fuel_Price": 0.0
}
test_df_filled = test_df_casted.fillna(fill_values)

# 3. Date & Categorical Features
test_df_clean = test_df_filled.withColumn("Date", col("Date").cast("date"))
test_df_clean = (test_df_clean
    .withColumn("Year", year("Date"))
    .withColumn("Month", month("Date"))
    .withColumn("WeekOfYear", weekofyear("Date"))
)

# Handle Type (Index)
indexer = StringIndexer(inputCol="Type", outputCol="TypeIndex", handleInvalid="keep")
indexer_model = indexer.fit(stores_df)
test_df_indexed = indexer_model.transform(test_df_clean)

# Handle IsHoliday (Boolean -> Int)
test_df_final = test_df_indexed.withColumn("IsHolidayInt", col("IsHoliday").cast(IntegerType()))

# =========================================================
# STEP 3: PREPARE TRAINING DATA (MATCHING SCHEMA)
# =========================================================

# Ensure Training Data has exact same schema/casts as Test Data
train_df_clean = model_df
for c_name in numeric_cols:
    if c_name in train_df_clean.columns:
        train_df_clean = train_df_clean.withColumn(c_name, col(c_name).cast(DoubleType()))

train_df_clean = train_df_clean.fillna(fill_values)

if "IsHolidayInt" not in train_df_clean.columns:
    train_df_clean = train_df_clean.withColumn("IsHolidayInt", col("IsHoliday").cast(IntegerType()))

if "TypeIndex" not in train_df_clean.columns:
    train_df_clean = indexer_model.transform(train_df_clean)

# =========================================================
# STEP 4: ASSEMBLE & FORECAST (SWAPPED TO XGBOOST)
# =========================================================

# Features without Lags (Since Test data has no history)
feature_cols_no_lag = [
    "Store", "Dept", "TypeIndex", "Size", "IsHolidayInt",
    "Temperature", "Fuel_Price", "CPI", "Unemployment",
    "MarkDown1", "MarkDown2", "MarkDown3", "MarkDown4", "MarkDown5",
    "Year", "Month", "WeekOfYear"
]

assembler = VectorAssembler(inputCols=feature_cols_no_lag, outputCol="features_no_lag", handleInvalid="skip")

# Create final datasets
train_ready = assembler.transform(train_df_clean)
test_ready = assembler.transform(test_df_final)

# Train XGBoost on the "No-Lag" data
print("Training Forecast Model (No-Lag XGBoost)...")
xgb_forecast = SparkXGBRegressor(
    features_col="features_no_lag",  # Matches the assembler output
    label_col="Weekly_Sales",
    num_workers=2,
    max_depth=5,
    n_estimators=50,
    missing=0.0
)

xgb_forecast_model = xgb_forecast.fit(train_ready)

# Predict
print("Generating Forecasts using XGBoost...")
final_predictions = xgb_forecast_model.transform(test_ready)

print("Forecast Complete. Ready for Business Insights.")

# =========================================================
# STEP 5: VISUALIZE RESULTS
# =========================================================

forecast_agg = (final_predictions
    .groupBy("Date")
    .agg(_sum("prediction").alias("Predicted_Sales"))
    .orderBy("Date")
)

pdf_plot = forecast_agg.toPandas()

plt.figure(figsize=(12, 6))
plt.plot(pdf_plot["Date"], pdf_plot["Predicted_Sales"], label="Forecasted Sales", color='green', marker='o')
plt.title("Future Sales Forecast (Test Data)", fontsize=16)
plt.xlabel("Date")
plt.ylabel("Total Weekly Sales ($)")
plt.legend()
plt.grid(True, alpha=0.3)
plt.gca().yaxis.set_major_formatter(mtick.StrMethodFormatter('${x:,.0f}'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

from pyspark.sql.functions import format_number

# Create a formatted version just for display
# format_number(col, 2) adds commas and rounds to 2 decimal places
forecast_display = forecast_agg.withColumn("Predicted_Sales", format_number("Predicted_Sales", 2))

print("\n--- Forecast Data Sample (Readable) ---")
forecast_display.show(5, truncate=False)

import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.ticker as mtick
from pyspark.sql.functions import sum as _sum, col

# --- Data Prep ---
# We aggregate predictions by Date
# The 'final_predictions' DataFrame, generated from test.csv, does not contain
# the 'Weekly_Sales' column, as test.csv only provides features for forecasting.
# Therefore, we can only plot the predicted sales.
daily_comparison = (final_predictions
    .groupBy("Date")
    .agg(
        _sum("prediction").alias("Predicted")
    )
    .orderBy("Date")
)

# Convert to Pandas for plotting
pdf_compare = daily_comparison.toPandas()

# --- Plotting ---
plt.figure(figsize=(15, 6))

# Plot Predicted Sales (The forecast for the test.csv data)
plt.plot(pdf_compare["Date"], pdf_compare["Predicted"],
         label="Model Forecast", color='#2ca02c', linestyle='-', linewidth=2) # Changed linestyle to solid for single line

plt.title("Sales Forecast for Test Data (2012-2013)", fontsize=16) # Adjusted title
plt.xlabel("Date", fontsize=12)
plt.ylabel("Weekly Sales ($)", fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)

# Format Y-axis as Dollars
plt.gca().yaxis.set_major_formatter(mtick.StrMethodFormatter('${x:,.0f}'))
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ---------------------------------------------------------
# VISUALIZATION: HISTORY (ACTUAL) vs. FUTURE (FORECAST)
# ---------------------------------------------------------
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib.ticker as mtick
from pyspark.sql.functions import sum as _sum, col, lit

# 1. Prepare Historical Data (The "Actuals" we DO have)
# We aggregate the training data (model_df) by Date
history_agg = (model_df
    .groupBy("Date")
    .agg(_sum("Weekly_Sales").alias("Sales"))
    .withColumn("Type", lit("Historical Actuals"))
    .orderBy("Date")
)

# 2. Prepare Forecast Data (The "Predictions")
# We aggregate the predictions (final_predictions) by Date
forecast_agg = (final_predictions
    .groupBy("Date")
    .agg(_sum("prediction").alias("Sales"))
    .withColumn("Type", lit("Future Forecast"))
    .orderBy("Date")
)

# 3. Convert to Pandas for Plotting
pdf_history = history_agg.toPandas()
pdf_forecast = forecast_agg.toPandas()

# 4. Plotting
plt.figure(figsize=(16, 6))

# Plot History (Blue Line)
plt.plot(pdf_history["Date"], pdf_history["Sales"],
         label="Historical Sales (Actual)", color='#1f77b4', linewidth=2)

# Plot Forecast (Red Dashed Line)
# This shows where the model thinks sales are going next
plt.plot(pdf_forecast["Date"], pdf_forecast["Sales"],
         label="Future Forecast (Predicted)", color='#d62728', linestyle='--', linewidth=2, marker='o', markersize=4)

# Formatting
plt.title("Sales Trajectory: Historical Performance vs. Future Forecast", fontsize=16)
plt.xlabel("Date", fontsize=12)
plt.ylabel("Total Weekly Sales ($)", fontsize=12)
plt.legend(fontsize=12)
plt.grid(True, alpha=0.3)

# Format Y-axis as Dollars
plt.gca().yaxis.set_major_formatter(mtick.StrMethodFormatter('${x:,.0f}'))
plt.xticks(rotation=45)
plt.tight_layout()

# Show the plot
plt.savefig("history_vs_forecast.png")
plt.show()

"""---



---

## Part 5: Business Insights

### 1. Store Performance Analysis

_Goal: Answer which stores will perform best/worst?_

- **The Insight:** This module aggregates projected revenue to identify high-velocity locations versus underperforming ones. It moves beyond historical data to forecast future contribution to the bottom line.

- **Strategic Application:**

  - Logistics Priority: The "Top 5 Stores" should receive priority shipping windows and dedicated fleet resources to prevent stockouts during high-demand periods.

  - Operational Audits: The "Bottom 5 Stores" trigger a root-cause analysis. Is it a location issue, a management issue, or a stock assortment issue? These stores may require renovation or closure if profitability targets aren't met.
"""

from pyspark.sql.functions import sum as _sum, col, desc, avg, count, format_number
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# --- ANALYSIS 1: STORE PERFORMANCE ---
# 1. Aggregate Future Sales by Store
store_stats = final_predictions.groupBy("Store") \
    .agg(_sum("prediction").alias("Total_Projected_Sales")) \
    .orderBy(desc("Total_Projected_Sales"))

# 2. Get Top 5 and Bottom 5
top_5_stores = store_stats.limit(5).toPandas()
bottom_5_stores = store_stats.orderBy(col("Total_Projected_Sales").asc()).limit(5).toPandas()

# 3. Display Data
print("--- TOP 5 PERFORMING STORES (PROJECTED) ---")
store_stats.withColumn("Total_Projected_Sales", format_number("Total_Projected_Sales", 2)).show(5)

print("--- BOTTOM 5 PERFORMING STORES (PROJECTED) ---")
store_stats.orderBy(col("Total_Projected_Sales").asc()) \
    .withColumn("Total_Projected_Sales", format_number("Total_Projected_Sales", 2)).show(5)

# 4. Visualization (Bar Chart)
plt.figure(figsize=(14, 6))

# Subplot 1: Top 5
plt.subplot(1, 2, 1)
sns.barplot(x='Store', y='Total_Projected_Sales', data=top_5_stores, palette='Greens_r', order=top_5_stores['Store'])
plt.title("Top 5 Stores (Highest Revenue)", fontsize=14)
plt.ylabel("Projected Sales ($)")
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1e6:.1f}M'))

# Subplot 2: Bottom 5
plt.subplot(1, 2, 2)
sns.barplot(x='Store', y='Total_Projected_Sales', data=bottom_5_stores, palette='Reds_r', order=bottom_5_stores['Store'])
plt.title("Bottom 5 Stores (Needs Attention)", fontsize=14)
plt.ylabel("Projected Sales ($)")
plt.gca().yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'${x/1e6:.1f}M'))

plt.tight_layout()
plt.show()

"""### 2. Department (Product) Analysis
_Goal: Answer which departments need restocking vs. marketing help?_

- **The Insight:** This identifies which product categories (Departments) drive the bulk of the revenue. In retail, typically 20% of the products drive 80% of the sales (Pareto Principle).

- **Strategic Application:**

  - Inventory Optimization: Top departments (e.g., Grocery, Electronics) require "Just-in-Time" inventory replenishment systems with higher safety stock levels.

  - Marketing Focus: Bottom-performing departments shouldn't just be ignored; they are candidates for "Bundle Promotions" (e.g., buy a TV, get a discount on the underperforming Accessories dept) or strategic clearance to free up shelf space.
"""

from pyspark.sql.functions import sum as _sum, col, desc, format_number
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns

# --- ANALYSIS 2: DEPARTMENT PERFORMANCE ---
# 1. Aggregate Future Sales by Dept
dept_stats = final_predictions.groupBy("Dept") \
    .agg(_sum("prediction").alias("Total_Projected_Sales")) \
    .orderBy(desc("Total_Projected_Sales"))

# 2. Get Insights (Convert to Pandas for plotting)
top_5_depts = dept_stats.limit(5).toPandas()
bottom_5_depts = dept_stats.orderBy(col("Total_Projected_Sales").asc()).limit(5).toPandas()

# 3. Display Data Tables
print("--- TOP 5 DEPARTMENTS - Products (High Inventory Priority) ---")
dept_stats.withColumn("Total_Projected_Sales", format_number("Total_Projected_Sales", 2)).show(5)

print("--- BOTTOM 5 DEPARTMENTS - Products (Marketing Focus Needed) ---")
dept_stats.orderBy(col("Total_Projected_Sales").asc()) \
    .withColumn("Total_Projected_Sales", format_number("Total_Projected_Sales", 2)).show(5)

# 4. Visualization
plt.figure(figsize=(16, 7))

# --- Subplot 1: Top 5 Departments ---
plt.subplot(1, 2, 1)
sns.barplot(x='Dept', y='Total_Projected_Sales', data=top_5_depts, palette='Blues_r', order=top_5_depts['Dept'])
plt.title("Top 5 Products (Best Sellers)", fontsize=14)
plt.xlabel("Department ID")
plt.ylabel("Projected Sales ($)")
plt.grid(axis='y', alpha=0.3)

# FIX: Format Y-axis with Dollars and Commas
plt.gca().yaxis.set_major_formatter(mtick.StrMethodFormatter('${x:,.0f}'))


# --- Subplot 2: Bottom 5 Departments ---
plt.subplot(1, 2, 2)
sns.barplot(x='Dept', y='Total_Projected_Sales', data=bottom_5_depts, palette='Oranges_r', order=bottom_5_depts['Dept'])
plt.title("Bottom 5 Products (Lowest Revenue)", fontsize=14)
plt.xlabel("Department ID")
plt.ylabel("Projected Sales ($)")
plt.grid(axis='y', alpha=0.3)

# FIX: Format Y-axis with Dollars and Commas
plt.gca().yaxis.set_major_formatter(mtick.StrMethodFormatter('${x:,.0f}'))

plt.tight_layout()
plt.show()

"""### 3. "The Holiday Lift"
_Retail managers always ask, "How much extra staff do I need for the holidays?" This part provides the average weekly sales for Holiday Weeks vs. Non-Holiday Weeks in our forecast._

- **The Insight:** Using a productivity metric (Sales per Employee), this converts "Revenue Forecasts" into "Headcount Requirements." It highlights exactly where and when the current workforce will be overwhelmed.

- **Strategic Application:**

  - Proactive Hiring: Instead of reacting to long lines, HR can launch hiring campaigns 3–4 weeks early for the specific stores identified as high-risk.

  - Cost Control: It prevents "blanket hiring." Stores that don't show a significant holiday lift (as seen in the data) are flagged as "No Surge Needed," saving payroll budget.
"""

# --- ANALYSIS 3: HOLIDAY IMPACT FORECAST ---
# Group by IsHolidayInt to compare averages
holiday_impact = final_predictions.groupBy("IsHolidayInt") \
    .agg(avg("prediction").alias("Avg_Weekly_Sales")) \
    .withColumn("Condition", col("IsHolidayInt").cast("string")) # Convert to string for labels

# Convert to Pandas
pdf_holiday = holiday_impact.toPandas()

# Map 0 -> Regular Week, 1 -> Holiday
pdf_holiday['Condition'] = pdf_holiday['Condition'].map({'0': 'Regular Week', '1': 'Holiday Week'})

# Display
print("--- HOLIDAY vs. REGULAR SALES FORECAST ---")
holiday_impact.withColumn("Avg_Weekly_Sales", format_number("Avg_Weekly_Sales", 2)).show()

# Visualize
plt.figure(figsize=(8, 5))
sns.barplot(x='Condition', y='Avg_Weekly_Sales', data=pdf_holiday, palette=['gold', 'grey'])
plt.title("Projected Impact of Holidays on Weekly Revenue", fontsize=14)
plt.ylabel("Average Sales per Store/Dept ($)")
plt.grid(axis='y', alpha=0.3)
plt.show()

"""#### Workforce Planning Analysis (Staffing Calculator)"""

from pyspark.sql.functions import avg, col, sum as _sum, round as _round, ceil, desc
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# --- UPDATED ASSUMPTIONS ---
# Walmart Metric: ~$260k revenue/year per employee = ~$5,000/week
SALES_PER_FTE = 5000

# --- STEP 1: CALCULATE TOTAL WEEKLY SALES PER STORE (The Missing Step) ---
# First, roll up departments to get the full Store Weekly Revenue
store_weekly_sales = final_predictions.groupBy("Store", "Date", "IsHolidayInt") \
    .agg(_sum("prediction").alias("Total_Store_Sales"))

# --- STEP 2: AVERAGE REGULAR VS HOLIDAY SALES ---
# Now compare the weeks
store_comparison = store_weekly_sales.groupBy("Store") \
    .pivot("IsHolidayInt") \
    .agg(avg("Total_Store_Sales")) \
    .na.fill(0) \
    .withColumnRenamed("0", "Regular_Sales") \
    .withColumnRenamed("1", "Holiday_Sales")

# --- STEP 3: CALCULATE HEADCOUNT ---
# Use ceil() to be safe (always round up people)
staffing_analysis = store_comparison \
    .withColumn("Regular_Staff", ceil(col("Regular_Sales") / SALES_PER_FTE)) \
    .withColumn("Holiday_Staff", ceil(col("Holiday_Sales") / SALES_PER_FTE)) \
    .withColumn("Extra_Hires_Needed", col("Holiday_Staff") - col("Regular_Staff"))

# --- STEP 4: REPORTING ---
top_hiring_needs = staffing_analysis.orderBy(desc("Extra_Hires_Needed")).limit(10).toPandas()

print("--- CORRECTED STORE-LEVEL WORKFORCE PLANNING ---")
print(f"Assumption: 1 Staff Member handles ${SALES_PER_FTE:,.0f} revenue/week")
print("-" * 85)
print(f"{'Store':<6} | {'Regular Staff':<15} | {'Holiday Staff':<15} | {'RECOMMENDATION (HIRES)':<25}")
print("-" * 85)

for index, row in top_hiring_needs.iterrows():
    store_id = row['Store']
    reg_staff = int(row['Regular_Staff'])
    hol_staff = int(row['Holiday_Staff'])
    hires = int(row['Extra_Hires_Needed'])

    rec = f"HIRE {hires} TEMP STAFF" if hires > 0 else "NO SURGE NEEDED"
    print(f"{store_id:<6} | {reg_staff:<15} | {hol_staff:<15} | {rec:<25}")

# --- STEP 5: VISUALIZATION ---
plot_data = top_hiring_needs.melt(id_vars="Store",
                                  value_vars=["Regular_Staff", "Holiday_Staff"],
                                  var_name="Season", value_name="Staff_Count")

plot_data["Season"] = plot_data["Season"].map({
    "Regular_Staff": "Baseline Staff",
    "Holiday_Staff": "Holiday Peak Staff"
})

plt.figure(figsize=(14, 7))
sns.barplot(x='Store', y='Staff_Count', hue='Season', data=plot_data, palette=['#95a5a6', '#e74c3c'])
plt.title("Workforce Surge Requirements (Top 10 High-Volume Stores)", fontsize=16)
plt.ylabel("Total Store Headcount", fontsize=12)
plt.xlabel("Store ID", fontsize=12)
plt.legend(title="Staffing Level")
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""### 4. Localized Assortment Planning
_Focus on specific products for specific stores._

- **The Business Problem:** Store A might be in a college town where "Electronics" sell best. Store B might be in a rural area where "Automotive" sells best. If you send the same inventory to both, Store A runs out of laptops, and Store B is stuck with unsold tires.

- **The Solution:** We will calculate the Top 3 Departments for EVERY Store individually.
"""

from pyspark.sql.window import Window
from pyspark.sql.functions import rank, col, desc

# --- HYPER-LOCALIZED ASSORTMENT PLANNING ---

# 1. Aggregate Sales by Store AND Dept
store_dept_sales = final_predictions.groupBy("Store", "Dept") \
    .agg(_sum("prediction").alias("Projected_Sales"))

# 2. Define Window Spec (Partition by Store, Order by Sales)
# This acts like a "Reset" button for every new Store ID
window_spec = Window.partitionBy("Store").orderBy(desc("Projected_Sales"))

# 3. Rank Departments within each Store
ranked_depts = store_dept_sales.withColumn("Rank", rank().over(window_spec))

# 4. Filter for the Top 3 Depts per Store
top_3_per_store = ranked_depts.filter(col("Rank") <= 3)

# 5. Convert to Pandas for Visualization/Reporting
pdf_localized = top_3_per_store.toPandas()

# --- REPORTING ---
print("--- HYPER-LOCALIZED INVENTORY STRATEGY ---")
print("Identifying the 'Hero Products' for specific locations")
print("-" * 60)
print(f"{'Store':<10} | {'Rank':<5} | {'Dept':<10} | {'Projected Sales':<15}")
print("-" * 60)

# Show just the first 3 stores as an example
unique_stores = pdf_localized['Store'].unique()[:3]
for s in unique_stores:
    subset = pdf_localized[pdf_localized['Store'] == s]
    for index, row in subset.iterrows():
        print(f"{row['Store']:<10} | {row['Rank']:<5} | {row['Dept']:<10} | ${row['Projected_Sales']:<15,.0f}")
    print("-" * 60)

# --- VISUALIZATION: Top Depts for Store 20 vs Store 14 ---
# Let's compare two different high-volume stores to show they are different
sample_stores = [20, 14]
plot_data = pdf_localized[pdf_localized['Store'].isin(sample_stores)]

plt.figure(figsize=(10, 6))
sns.barplot(x='Store', y='Projected_Sales', hue='Dept', data=plot_data, palette='viridis')
plt.title("Localized Assortment: Top 3 Departments vary by Store", fontsize=14)
plt.ylabel("Projected Sales ($)")
plt.xlabel("Store ID")
plt.legend(title="Department ID")
plt.grid(axis='y', alpha=0.3)
plt.show()

"""#### Facet Grid for top 3 products from each store


"""

from pyspark.sql.window import Window
from pyspark.sql.functions import rank, col, desc, sum as _sum
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# --- STEP 1: PREPARE DATA (PySpark) ---

# 1. Aggregate Projected Sales by Store & Dept
store_dept_sales = final_predictions.groupBy("Store", "Dept") \
    .agg(_sum("prediction").alias("Total_Sales"))

# 2. Rank Departments within each Store (1st, 2nd, 3rd best sellers)
window_spec = Window.partitionBy("Store").orderBy(desc("Total_Sales"))

ranked_depts = store_dept_sales.withColumn("Rank", rank().over(window_spec))

# 3. Filter for TOP 3 only
# (Keeping it to 3 makes the small graphs readable. 5 is too crowded for 45 plots)
top_3_per_store = ranked_depts.filter(col("Rank") <= 3)

# 4. Convert to Pandas for Plotting
pdf_small_multiples = top_3_per_store.toPandas()

# Sort by Store for cleaner plotting order
pdf_small_multiples = pdf_small_multiples.sort_values(by=["Store", "Rank"])

# --- STEP 2: VISUALIZATION (Seaborn FacetGrid) ---

# Define the Grid
# col="Store": Creates a new plot for each Store
# col_wrap=5: Arranges them in 5 columns (resulting in 9 rows for 45 stores)
# sharex=False: Allows each store to have its own unique Top 3 Depts on the X-axis
# sharey=False: Allows y-axis to scale independently (Small stores vs Big stores)
g = sns.FacetGrid(pdf_small_multiples, col="Store", col_wrap=5,
                  sharex=False, sharey=False, height=2.5, aspect=1.3)

# Map the Barplot onto the grid
g.map_dataframe(sns.barplot, x="Dept", y="Total_Sales", palette="viridis")

# --- STEP 3: FORMATTING ---

# Add Titles and Axis Labels
g.set_titles(col_template="Store {col_name}") # Titles like "Store 1", "Store 2"
g.set_axis_labels("Dept ID", "Sales")

# Format Y-Axis to Dollars (e.g., $5M)
for ax in g.axes.flat:
    ax.yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: f'${x/1e6:.1f}M'))

    # Rotate X-axis labels (Dept IDs) so they don't overlap
    for label in ax.get_xticklabels():
        label.set_rotation(0)

# Adjust Layout
plt.subplots_adjust(top=0.96) # Make room for the main title
g.fig.suptitle("Hyper-Localized Assortment: Top 3 Departments per Store", fontsize=20, fontweight='bold')

plt.show()

"""### 5. Capacity Planning Matrix (Scatter Plot)

A "Capacity vs. Demand Matrix" is the standard way supply chain managers determine restocking frequency.

- **The Logic:** You compare the physical space of the store (Size) against the volume of product moving out the door (Projected Sales).

- **The Business Insight:**

  - High Sales + Small Size: These stores are "Restocking Bottlenecks." They physically cannot hold enough inventory to last a week. They need frequent, small deliveries (e.g., daily trucks instead of weekly).

  - Low Sales + Large Size: These stores have "Wasted Space." They are holding too much safety stock and incurring unnecessary holding costs.
"""

from pyspark.sql.functions import countDistinct, sum as _sum
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick

# --- STEP 1: AGGREGATE DATA ---
# We need to know:
# 1. Total Demand (Sum of Sales)
# 2. Product Variety (Count of Active Depts)
# 3. Store Capacity (Size - strictly from the stores_df)

# Aggregate Sales & Product Count
store_demand = final_predictions.groupBy("Store") \
    .agg(
        _sum("prediction").alias("Total_Projected_Sales"),
        countDistinct("Dept").alias("Active_Departments")
    )

# Join with Store Metadata (Size, Type)
# Note: Ensure stores_df is available (loaded in previous steps)
capacity_matrix = store_demand.join(stores_df, on="Store", how="left").toPandas()

# --- STEP 2: DEFINE ZONES (THRESHOLDS) ---
avg_size = capacity_matrix['Size'].mean()
avg_sales = capacity_matrix['Total_Projected_Sales'].mean()

# --- STEP 3: VISUALIZATION ---
plt.figure(figsize=(14, 8))

# Scatter Plot
# X = Physical Capacity (Size)
# Y = Outbound Demand (Sales)
# Hue = Store Type (Operational Complexity)
# Size = Product Variety (More Depts = More complex restocking)
sns.scatterplot(
    data=capacity_matrix,
    x='Size',
    y='Total_Projected_Sales',
    hue='Type',
    style='Type',
    size='Active_Departments',
    sizes=(50, 400),
    palette='viridis',
    alpha=0.8
)

# Add Quadrant Lines (The "Average" baselines)
plt.axvline(avg_size, color='grey', linestyle='--', alpha=0.5)
plt.axhline(avg_sales, color='grey', linestyle='--', alpha=0.5)

# Annotate Quadrants
plt.text(avg_size * 1.1, avg_sales * 1.5, "HEALTHY\n(Large Size, High Sales)", fontsize=10, color='green', fontweight='bold')
plt.text(avg_size * 0.5, avg_sales * 1.5, "CRITICAL BOTTLENECK\n(Small Size, High Sales)\n*Needs Daily Restocking*", fontsize=10, color='red', fontweight='bold')
plt.text(avg_size * 1.1, avg_sales * 0.2, "UNDER-UTILIZED\n(Large Size, Low Sales)", fontsize=10, color='orange', fontweight='bold')

# Formatting
plt.title("Supply Chain Risk Matrix: Restocking Capacity vs. Demand", fontsize=16)
plt.xlabel("Store Size (sq ft) - Physical Capacity", fontsize=12)
plt.ylabel("Projected Weekly Sales ($) - Inventory Demand", fontsize=12)
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(lambda x, p: f'${x/1e6:.1f}M'))
plt.gca().xaxis.set_major_formatter(mtick.StrMethodFormatter('{x:,.0f}'))

plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left', title="Store Profile")
plt.tight_layout()
plt.show()

# --- STEP 4: IDENTIFY THE 'RED ZONE' STORES ---
# These are stores with Size < Average BUT Sales > Average
critical_stores = capacity_matrix[
    (capacity_matrix['Size'] < avg_size) &
    (capacity_matrix['Total_Projected_Sales'] > avg_sales)
].sort_values(by='Total_Projected_Sales', ascending=False)

print("--- CRITICAL RESTOCKING PRIORITIES (Small Stores / High Volume) ---")
print("Action: Increase delivery frequency to prevent stockouts.")
print("-" * 60)
print(f"{'Store':<6} | {'Type':<5} | {'Size (sq ft)':<15} | {'Projected Sales':<20}")
print("-" * 60)
for index, row in critical_stores.iterrows():
    print(f"{row['Store']:<6} | {row['Type']:<5} | {row['Size']:<15,.0f} | ${row['Total_Projected_Sales']:<20,.0f}")

"""## 6. Limitations & Assumptions:

Our analysis relies on standard retail operational heuristics. Specifically, we estimate workforce requirements based on a productivity benchmark of $5,000 weekly revenue per FTE. Furthermore, in the absence of real-time inventory levels, we assume that deviations from the network-average sales volume represent a direct gap in supply chain replenishment needs. Finally, for the future forecast, we assume that structural store attributes (Size, Type, Location) remain predictive of sales volume even when immediate historical sales data is unavailable for lag generation.


1. Data Processing Assumptions
- Missing Markdown Values imply "No Promotion":

  - The Assumption: The dataset contained null values for MarkDown1-5. We assumed these nulls represented zero promotional activity rather than missing/corrupted data.

  - Why it matters: This justified filling nulls with 0.0 instead of imputing them with the mean or dropping the rows.

- Negative Sales represent Returns:

  - The Assumption: The dataset contains negative Weekly_Sales. We assumed these represent customer returns and kept them in the dataset to calculate true Net Revenue.

  - Why it matters: Removing them would inflate the revenue projections.

- Stationarity of Store Size:

  - The Assumption: We assumed that the Size (square footage) of a store remained constant throughout the 3-year period (no remodels or expansions).

2. Modeling & Forecasting Assumptions
- The "Cold Start" Constraint (Crucial):

  - The Assumption: For the future test.csv data, we lacked immediate historical sales data (previous weeks). We assumed that structural features (Store Type, Size, Dept, Holidays) are sufficient proxies for demand when "Lag" features are unavailable.

  - Why it matters: This explains why you used a "No-Lag" version of the model for the final forecast, even though the "Lagged" version had better RMSE in validation.

- Seasonality is Cyclic:

  - The Assumption: We assumed that consumer buying behavior during holidays (Super Bowl, Thanksgiving, Christmas) remains consistent year-over-year.

  - Why it matters: This justifies training on 2010–2011 patterns to predict 2012–2013 outcomes.

3. Business & Operational Assumptions (The "Heuristics")
- Productivity Heuristic ($5,000/week):

  - The Assumption: We assumed that one Full-Time Equivalent (FTE) employee generates/handles approximately $5,000 in weekly revenue (derived from Walmart's annual revenue per employee statistics).

  - Why it matters: This is the basis of your "Hiring Surge" recommendation. If this number is wrong, your headcount recommendation changes.

- Inventory Capacity Proxy:

  - The Assumption: We used the "Average Store Sales" as a proxy for the Standard Inventory Load. Any demand significantly above this average is assumed to require "Extra Replenishment."

  - Why it matters: Without real inventory data (e.g., "we have 500 units in stock"), this relative comparison is the only way to flag "High Risk" stores.

- Space = Capacity:

  - The Assumption: In your "Capacity Matrix" scatter plot, we assumed that Store Size is directly correlated with Backroom Storage Capacity.

  - Why it matters: It validates the recommendation that "Small Stores with High Sales" need frequent deliveries because they physically cannot store safety stock.

## 7. Conclusion:

I. Operational Efficiency (Workforce Planning)
- Insight: Your store-level analysis shows that the "Holiday Lift" is not uniform. Some stores explode in volume, while others remain flat.

- Recommendation: Move away from blanket hiring. Implement a Tiered Hiring Strategy:

  - Tier 1 (High Surge): Stores like #20 and #4 require 45+ temporary staff hired 3 weeks pre-holiday.

  - Tier 2 (Flat Demand): Stores like #33 and #43 should operate on standard headcount to save payroll costs.

- Metric: Use the "Sales per FTE" benchmark ($5,000/week) to dynamically adjust rosters based on the XGBoost weekly forecast.

II. Supply Chain Optimization (Inventory)
- Insight: The "Capacity vs. Demand Matrix" identifies a critical risk group: Small Stores with High Volume (Top-Left Quadrant).

- Recommendation:

  - For "Red Zone" Stores: Implement Cross-Docking. Inventory should move directly from the inbound truck to the sales floor, bypassing the backroom entirely, as they lack physical storage capacity.

  - For "Green Zone" Stores: These locations should serve as Hubs. They can hold excess safety stock to support the smaller satellite stores nearby.

III. Merchandising (Localized Assortment)
- Insight: The "Hyper-Localized" analysis proves that Top 3 Departments vary by location. Store 14 relies on Dept 92 (Grocery), while Store 45 relies heavily on Dept 95 (Electronics).

- Recommendation: End the "One Planogram Fits All" approach.

  - Action: Customize the shelf-space allocation. Store 45 should dedicate 15% more floor space to Electronics during Q4, reducing Apparel space, whereas Store 14 should expand Grocery aisles.



---



This project demonstrates that Walmart's sales are driven primarily by historical momentum (Lags) and seasonal events, rather than macro-economic indicators like CPI or Fuel Price. By implementing an XGBoost model, we achieved a prediction error (RMSE) of 3,424, significantly outperforming baseline linear and Tree based models.

The business value of this model extends beyond accuracy. It enables a transition from reactive management to predictive operations: allowing HR to staff stores precisely based on projected surge, Supply Chain to allocate inventory based on store capacity constraints, and Merchandising to localize product assortments. Implementing these data-driven strategies could reduce payroll waste and stockouts, directly improving the store's bottom line.
"""